### Задание 1.

In [9]:
import numpy as np

In [10]:
A = np.array([[1,4,7],[2,5,8],[3,6,9]])
def standard_scaler(A):
    return (A - A.mean(axis=0)) / A.std(axis=0)
print(standard_scaler(A))

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


### Задание 2.

In [40]:
A = np.array([[0, 2, 4, 1, 2],
       [6, 5, 6, 1, 7],
       [4, 4, 2, 7, 7],
       [1, 4, 2, 8, 2],
       [4, 3, 1, 4, 6],
       [3, 3, 9, 9, 1],
       [5, 1, 1, 9, 2],
       [0, 0, 0, 9, 5],
       [5, 3, 6, 4, 9],
       [8, 8, 2, 7, 2],
       [7, 9, 7, 4, 1],
       [3, 5, 7, 0, 2],
       [0, 2, 2, 5, 5],
       [4, 8, 0, 9, 0]])
def get_corcoefs(A):
    R1 = np.corrcoef(A)
    return R1[np.triu_indices(4)]
get_corcoefs(A)

array([ 1.        ,  0.28747979, -0.48202707, -0.15691148,  1.        ,
       -0.39336863, -0.95422628,  1.        ,  0.5119947 ,  1.        ])

In [101]:
Z = np.zeros((10,10),dtype=int)

#Z[1::2,::2] = 7
#print(Z)


#np.where(Z[:,0] != 0)[0]
def nul_column():
    Z = np.zeros((10,10),dtype=int)
    Z[1::2,::2] = 7
    print(Z)
    print(np.where(Z[:,0] != 0))
nul_column()

[[0 0 0 0 0 0 0 0 0 0]
 [7 0 7 0 7 0 7 0 7 0]
 [0 0 0 0 0 0 0 0 0 0]
 [7 0 7 0 7 0 7 0 7 0]
 [0 0 0 0 0 0 0 0 0 0]
 [7 0 7 0 7 0 7 0 7 0]
 [0 0 0 0 0 0 0 0 0 0]
 [7 0 7 0 7 0 7 0 7 0]
 [0 0 0 0 0 0 0 0 0 0]
 [7 0 7 0 7 0 7 0 7 0]]
(array([1, 3, 5, 7, 9], dtype=int64),)
